server:
  port: 8083

spring:
  data:
    redis:
      cluster:
        nodes:
          - localhost:6380
          - localhost:6381
          - localhost:6382
          - localhost:6383
          - localhost:6384
          - localhost:6385
      repositories:
        enabled: false

  kafka:
    bootstrap-servers: localhost:19094,localhost:19095,localhost:19096
    consumer:
      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      properties:
        allow.auto.create.topics: false
        enable.auto.commit: false
        partition.assignment.strategy: org.apache.kafka.clients.consumer.CooperativeStickyAssignor
      group-id: timeline-server